//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapClientUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoapClientUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Toggle Fullscreen.
        /// </summary>
        public static string App_Fullscreen {
            get {
                return ResourceManager.GetString("App_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errors.
        /// </summary>
        public static string App_Menu_Errors {
            get {
                return ResourceManager.GetString("App_Menu_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Requests gone bad.
        /// </summary>
        public static string App_Menu_Errors_Description {
            get {
                return ResourceManager.GetString("App_Menu_Errors_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Computation report.
        /// </summary>
        public static string App_Menu_Processed {
            get {
                return ResourceManager.GetString("App_Menu_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Computation request outcomes.
        /// </summary>
        public static string App_Menu_Processed_Description {
            get {
                return ResourceManager.GetString("App_Menu_Processed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Minimize.
        /// </summary>
        public static string App_Minimize {
            get {
                return ResourceManager.GetString("App_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Processed Requests Section.
        /// </summary>
        public static string App_Processed {
            get {
                return ResourceManager.GetString("App_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Date Time.
        /// </summary>
        public static string App_Processed_DateTime {
            get {
                return ResourceManager.GetString("App_Processed_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Job Number.
        /// </summary>
        public static string App_Processed_Job {
            get {
                return ResourceManager.GetString("App_Processed_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Left Design.
        /// </summary>
        public static string App_Processed_Left_Design {
            get {
                return ResourceManager.GetString("App_Processed_Left_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Result Message.
        /// </summary>
        public static string App_Processed_Result {
            get {
                return ResourceManager.GetString("App_Processed_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Right Design.
        /// </summary>
        public static string App_Processed_Right_Design {
            get {
                return ResourceManager.GetString("App_Processed_Right_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Service is Running.
        /// </summary>
        public static string App_Processed_Service_Running {
            get {
                return ResourceManager.GetString("App_Processed_Service_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Service is Stopped.
        /// </summary>
        public static string App_Processed_Service_Stopped {
            get {
                return ResourceManager.GetString("App_Processed_Service_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Refresh.
        /// </summary>
        public static string App_Refresh {
            get {
                return ResourceManager.GetString("App_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Installation Management.
        /// </summary>
        public static string App_Settings_Service_Installation {
            get {
                return ResourceManager.GetString("App_Settings_Service_Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select File.
        /// </summary>
        public static string App_Settings_Service_Installation_File {
            get {
                return ResourceManager.GetString("App_Settings_Service_Installation_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Install.
        /// </summary>
        public static string App_Settings_Service_Installation_Install {
            get {
                return ResourceManager.GetString("App_Settings_Service_Installation_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Service Path.
        /// </summary>
        public static string App_Settings_Service_Installation_Path {
            get {
                return ResourceManager.GetString("App_Settings_Service_Installation_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Uninstall.
        /// </summary>
        public static string App_Settings_Service_Installation_Uninstall {
            get {
                return ResourceManager.GetString("App_Settings_Service_Installation_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Parameters.
        /// </summary>
        public static string App_Settings_Service_Parameters {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Analysis Path.
        /// </summary>
        public static string App_Settings_Service_Parameters_Analysis {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CAS Endpoint.
        /// </summary>
        public static string App_Settings_Service_Parameters_Cas {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_Cas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error Path.
        /// </summary>
        public static string App_Settings_Service_Parameters_Error {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Output Format.
        /// </summary>
        public static string App_Settings_Service_Parameters_Format {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gax.
        /// </summary>
        public static string App_Settings_Service_Parameters_Gax {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_Gax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Input Path.
        /// </summary>
        public static string App_Settings_Service_Parameters_Input {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LapGax.
        /// </summary>
        public static string App_Settings_Service_Parameters_LapGax {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_LapGax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Output Path.
        /// </summary>
        public static string App_Settings_Service_Parameters_Output {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password.
        /// </summary>
        public static string App_Settings_Service_Parameters_Password {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Processed Path.
        /// </summary>
        public static string App_Settings_Service_Parameters_Processed {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a API Endpoint.
        /// </summary>
        public static string App_Settings_Service_Parameters_Service {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Surface Path.
        /// </summary>
        public static string App_Settings_Service_Parameters_Surface {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_Surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Username.
        /// </summary>
        public static string App_Settings_Service_Parameters_Username {
            get {
                return ResourceManager.GetString("App_Settings_Service_Parameters_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status Management.
        /// </summary>
        public static string App_Settings_Service_Status {
            get {
                return ResourceManager.GetString("App_Settings_Service_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start.
        /// </summary>
        public static string App_Settings_Service_Status_Start {
            get {
                return ResourceManager.GetString("App_Settings_Service_Status_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stop.
        /// </summary>
        public static string App_Settings_Service_Status_Stop {
            get {
                return ResourceManager.GetString("App_Settings_Service_Status_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Opto+ Client Service Management.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value cannot be empty.
        /// </summary>
        public static string App_Validations_Value_Cannot_Be_Empty {
            get {
                return ResourceManager.GetString("App_Validations_Value_Cannot_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid value.
        /// </summary>
        public static string App_Validations_Value_Invalid {
            get {
                return ResourceManager.GetString("App_Validations_Value_Invalid", resourceCulture);
            }
        }
    }
}
